services:
  - type: web
    name: fxpro-backend
    env: node
    region: oregon
    plan: starter       # use "starter" for free backend
    rootDir: backend    # <- points to the folder with package.json
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true

  - type: static
    name: fxpro-frontend
    env: static
    region: oregon
    rootDir: frontend
    autoDeploy: true
