services:
  - type: web
    name: fxpro-backend
    env: node
    region: oregon
    plan: starter       # free backend plan
    rootDir: backend    # points to your package.json
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true

  - type: static_site
    name: fxpro-frontend
    rootDir: frontend
    autoDeploy: true
