services:
  - type: web
    name: fxpro-backend
    env: node
    region: oregon
    plan: starter        # backend uses starter (NOT free)
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true

  - type: web
    name: fxpro-frontend
    env: static
    rootDir: frontend
    autoDeploy: true
