# render.yaml - for both backend and frontend

services:
  - type: web
    name: fxpro-backend
    env: node
    region: oregon   # change if needed
    plan: free       # choose your plan
    buildCommand: npm install
    startCommand: npm start
    rootDir: backend
    autoDeploy: true

  - type: web
    name: fxpro-frontend
    env: static
    region: oregon   # change if needed
    plan: free
    rootDir: frontend
    autoDeploy: true
